### ISSUE TITLE
Could not upload files via the Fileadmin in Azure

### ISSUE THREAD

**Issue by mobernberger** [dkd/typo3-cms-azure#1]
Hello,
we have deployed your Azure Image for testing purposes and now have the Problem, that we aren't unable to upload files directly from the backend. You have to upload the files via FTP to the Website.
I have attached two screenshots of the error from the fileadmin and from the logfiles.
![fileadmin-error](https://cloud.githubusercontent.com/assets/8603460/6324197/e4264578-bb36-11e4-89cc-fccfd6d41ec4.png)
![log-error](https://cloud.githubusercontent.com/assets/8603460/6324199/e86a9684-bb36-11e4-8aa2-af6de23dae8f.png)
Best Regards,
Michael

**Comment by sascha-egerer** [comment]
Hi Michael,

thank you for your report. We can reproduce this issue and will have a look at that.

Regards
Sascha

**Comment by sascha-egerer** [comment]
Hi Michael, the issue has been fixed. But we have to build a new Azure package which could take some time. As soon has the new package is available we will update this ticket.

Regards 
Sascha

**Comment by sascha-egerer** [comment]
Related TYPO3 Core issue https://review.typo3.org/#/c/37104/

**Comment by sascha-egerer** [comment]
Patch has been merged into the TYPO3 Core and is part of the upcoming 6.10 Release.
https://forge.typo3.org/issues/65230#change-250740
